### ISSUE TITLE
Detect and update the server if a newer version is available

### ISSUE THREAD

**Issue by rpelisse** [ansible-middleware/jws-ansible-playbook#44]
##### SUMMARY

If the playbook run on a target using an older version than the one configured, it should detect the discrepancy and, if configured to do so, update the installation.

##### ISSUE TYPE
 - Feature Idea

**Comment by guidograzioli** [comment]
The cause of this issue is that we allow to override the installation zipfile to a file name that does not contain the version.
`tomcat_zipfile: "tomcat.zip"`
There is no clean way to check if an arbitrarily named zipfile really contains what is declared in `tomcat_version`.

I think we should remove the option tomcat_zipfile completely; and instead rely on what filenames are provided by the download enpoints

**Comment by rpelisse** [comment]
I think we cannot get away without providing a way for user to have their own zipfile instead of our sane defaults. One use case I can see is an organization building its own, customized version of JWS, zipping in under my-org-java-server-1.1.zip. We need to have path for this use case.
However, yes, we should not have tomcat_zipfile has a mandatory parameters to provides, but more as an option.

**Comment by guidograzioli** [comment]
Parameter `tomcat_force_install` introduced in #80 allows to perform the update (no uninstall happens); setting a tomcat_version (and thus tomcat_home) which does not match with the contents of zipfile continues to throw an error. We might want to use a better wording than 'Destination directory /opt/apache-tomcat-X.X.X does not exist`?
