### ISSUE TITLE
Missing documentation for enabling HTTPS connector

### ISSUE THREAD

**Issue by csutherl** [ansible-middleware/jws-ansible-playbook#75]
##### SUMMARY
There isn't any documentation for how to use the HTTPS connector configuration that is available on the tomcat role and it doesn't work out of the box. Setting `tomcat_listen_https_enabled` to `True` enables the connector configuration, but expect a keystore that may not exist. The connector fails to start by default.

If you run the command from [Tomcat's SSL/TLS Configuration How-To](https://tomcat.apache.org/tomcat-9.0-doc/ssl-howto.html#Quick_Start) and drop the keystore that creates into `/etc/ssl/keystore.jks` then it works fine. Could we create a default keystore, or maybe set some variable that fails when it's not present to save users from not completing the HTTPS Connector config? Or we can solve the problem through docs.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
```

##### COLLECTION VERSION

`ansible-galaxy collection list` is not a valid command in my version.

##### STEPS TO REPRODUCE
Using the default playbook, set `tomcat_listen_https_enabled: True` and execute.

##### EXPECTED RESULTS
I expect that Tomcat would start and be accessible with HTTPS requests via port 8443.

##### ACTUAL RESULTS
Tomcat did no bind to 8443 due to the Connector init failing; there is no keystore added by default. You have to check the log to find out that it failed.

**Comment by csutherl** [comment]
If this is not expected to work, then it should we should provide more clear steps to make the feature useful.

**Comment by csutherl** [comment]
https://docs.ansible.com/ansible/latest/collections/community/general/java_keystore_module.html looks interesting :)

**Comment by rpelisse** [comment]
_There isn't any documentation for how to use the HTTPS connector configuration that is available on the tomcat role and it doesn't work out of the box. Setting tomcat_listen_https_enabled to True enables the connector configuration, but expect a keystore that may not exist. The connector fails to start by default._

Yes, we should, but keeping in mind the principle of not repeating available documentation, the documentation should say "that's how you enable HTTPS, please refer to this tomcat/jws documentation to ensure the cert/keys are properly installed first".


_https://docs.ansible.com/ansible/latest/collections/community/general/java_keystore_module.html looks interesting :)_

Oh, we went down that road a couple of weeks ago. I tried to build a fully automated Molecule testsuite, that would generate the requires key/cert, deploy them and run the server... The idea was to have a toggle option (gen_certs yes/no), so that user could simply generate the required files... But I had to give up because it ended up adding two collections as dependencies and it got quite cumbersome. In the end, we deemed easier to simply add the jks file to the Molecule test.

But, if the java_keystore is indeed provided, you are right, [all you need is to tomcat_listen_https_enabled toTrue](https://github.com/ansible-middleware/jws-ansible-playbook/blob/main/molecule/https/molecule.yml#L39)

**Comment by csutherl** [comment]
Thanks for replying @rpelisse :D Could we add a check for the keystore if you're using the `tomcat_listen_https_enabled` flag so that it fails to complete the execution rather than succeeding and not starting the Connector? Or could we check the log to see if the Connector started successfully?

**Comment by rpelisse** [comment]
Well, yes, we **could** but there is a caveat. So, if you run the playbook in "demo" mode and wants to enable HTTPS, this will works fine. But, now, if the user has overridden the default templates for the server.xml he or she may NOT use the same variable name as we do for the path. And suddenly, the playbook will fails because of a missing var that he or she never set. 

That being said, thinking out loud, we can certainly add a check that if the tomcat.listen.https.keystore is defined (and https enable) then it should point to an existing file. I'll give it a try asap.

**Comment by rpelisse** [comment]
Fixed by [PR78](https://github.com/ansible-middleware/jws-ansible-playbook/pull/78)

@csutherl please review the PR if you can :) ! (especially the documentation part in the jws/docs/README.md).
